name: pre-commit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/cache@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install Ceedling
        run: gem install ceedling
      - name: Run Format Validations
        uses: pre-commit/action@v3.0.0
      - name: Run Unit Tests
        run: ceedling clobber gcov:all utils:gcov
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: build/artifacts/gcov/report.xml
          reporter: jest-junit
